import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

function escapeTemplateLiteral(s: string): string {
    return s.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main(): Promise<void> {
    const __filename: string = fileURLToPath(import.meta.url);
    const __dirname: string = path.dirname(__filename);
    const entry: string = path.join(__dirname, "script.ts");
    const outFile: string = path.join(__dirname, "generated.ts");
    const result = await build({
        entryPoints: [entry],
        bundle: true,
        write: false,
        format: "iife",
        target: "esnext",
        sourcemap: false,
    });
    const js: string = result.outputFiles[0].text;
    const content = `// This file is generated by convert.ts. Do not edit manually.
    export const SCRIPT_JS: string = \`${escapeTemplateLiteral(js)}\`;`;
    await fs.writeFile(outFile, content, "utf8");
}

main().catch((err: unknown): never => {
    console.error(err);
    process.exit(1);
});
